### ISSUE TITLE
cannot duplicate result

### ISSUE THREAD

**Issue by blacksingular** [FeiSun/BERT4Rec#3]
I used the original code as well as the ml-1m data listed in the repo. But the loss didn't drop since 10000 iteration, final loss remained on about 5.12. Is there any preprocessing do I need to do before training? Thanks!

**Comment by xaram** [comment]
> I used the original code as well as the ml-1m data listed in the repo. But the loss didn't drop since 10000 iteration, final loss remained on about 5.12. Is there any preprocessing do I need to do before training? Thanks!

@blacksingular were you able to reproduce the results successfully?
